### ISSUE TITLE
Add groupMembership as relationship type to /persons endpoint

### ISSUE THREAD

**Issue by xandhen** [girgen/ss12000v2#113]
Currently there are two issues when dealing with students who lack an enrolment at a school unit which makes some scenarios more difficult.

1. When dealing with students who attend an activity at a school unit X where they lack an active enrolment, it will be difficult to map the person reference in the group membership to an actual person since these students are not exposed via the /persons endpoint. This is true for grundskola and gymnasieskola where in reality, an activity can be offered at a single school unit, but have members from multiple other school units. A so called shared resource issue.

2. When dealing with adult education (VUX) the students will not have an enrolment in any way, but they will attend a certain number of activities at the school unit. Their school unit relationship is therefor never defined by an enrolment, but only through active group memberships.

A proposed solution to this issue is to add a new value `groupMembership` to the parameter `relationship.entity.type`. In combination with this the definition of `relationship.organisation` should be expanded so that group memberships are taken into account.
This will allow the /persons endpoint to expose all persons with a relationship to the school unit and will also create a better symmetry with the expand parameter that already includes `groupMemberships` as an expand alternative.

**Comment by joesiltberg** [comment]
Sounds good to me!

My only thought is that the new relationship type (groupMembership) doesn't exactly match "students with a relationship to the school unit". If a student has an enrolment, but is temporarily (perhaps before school start) not a member of a group, I would assume that student isn't returned with this filter..?

If the use case is to fetch all students with a relation to the school unit, would you need to do two requests (one for enrolments and one for group memberships)?

Would a "studiesAt" relationship (meaning either enrolled or member of a group) better match the use case you have in mind?

Could also be worth considering a scenario where the consuming system doesn't have access to group memberships due to minimization of personal information.

**Comment by xandhen** [comment]
If you don't supply a value for the parameter `relationship.entity.type` the server would return all children/students that have either an enrolment, a placement or a group-membership and all personell with a duty or a group-membership and all custodians with a responsibleFor relationship to an enrolment or a placement at the organisation.

If you want a finer granularity, then you would need to make multiple calls. A more attractive solution for the future would be to allow multiple values of `relationship.entity.type` to adress this issue.

If the consumer can't digest all data, it will simply ignore that data in my view. E.g the consumer specifies the expand parameter to communicate what it wants to receive.

**Comment by girgen** [comment]
Committed.
